export const data = [
    {
        id: 1,
        img1: '/images/hb1.png',
        img2: '/images/hb2.png',
        imgAlt1: 'Yamaha Yzf-r6',
        imgAlt2: 'Suzuki Inazuma',
        model: 2000,
        modelName: 'Yamaha Yzf-r6',
        price: 20000,
        modelColor: 'Yellow',
        engineCapacity: 600,
        topSpeed: 250,
        fuelType: 'Petrol',
        weight: 190,
        brand: 'Yamaha'
    },
    {
        id: 2,
        img1: '/images/hb1.png',
        img2: '/images/hb3.png',
        imgAlt1: 'Yamaha Yzf-r6',
        imgAlt2: 'Suzuki Inazuma',
        model: 2012,
        modelName: 'Suzuki Inazuma',
        price: 20000,
        modelColor: 'Blue',
        engineCapacity: 250,
        topSpeed: 140,
        fuelType: 'Petrol',
        weight: 183,
        brand: 'Suzuki'
    },
    {
        id: 3,
        img1: '/images/hb1.png',
        img2: '/images/hb8.png',
        imgAlt1: 'Suzuki Inazuma',
        imgAlt2: 'Suzuki Inazuma',
        model: 2015,
        modelName: 'Suzuki Intruder',
        price: 10000,
        modelColor: 'Red',
        engineCapacity: 150,
        topSpeed: 120,
        fuelType: 'Petrol',
        weight: 148,
        brand: 'Suzuki'
    },
    {
        id: 4,
        img1: '/images/hb1.png',
        img2: '/images/hb9.png',
        imgAlt1: 'Honda CBR250',
        imgAlt2: 'Suzuki Inazuma',
        model: 2021,
        modelName: 'Honda CBR250',
        price: 30000,
        modelColor: 'Golden',
        engineCapacity: 250,
        topSpeed: 170,
        fuelType: 'Petrol',
        weight: 165,
        brand: 'Honda'
    },
    {
        id: 5,
        img1: '/images/hb1.png',
        img2: '/images/hb11.png',
        imgAlt1: 'Suzuki Gsx-r1000',
        imgAlt2: 'Honda CBR250',
        model: 2008,
        modelName: 'Suzuki Gsx-r1000',
        price: 15000,
        modelColor: 'Orange',
        engineCapacity: 1000,
        topSpeed: 299,
        fuelType: 'Petrol',
        weight: 203,
        brand: 'Suzuki'
    },
    {
        id: 6,
        img1: '/images/hb1.png',
        img2: '/images/hb1.png',
        imgAlt1: 'Yamaha Yzf-r6',
        imgAlt2: 'Suzuki Inazuma',
        model: 2005,
        modelName: 'Suzuki Hayabusa',
        price: 20000,
        modelColor: 'Black',
        engineCapacity: 1340,
        topSpeed: 312,
        fuelType: 'Petrol',
        weight: 264,
        brand: 'Suzuki'
    }
];
